Add new image with bison/flex as dependencies.
Update version info for the builds (#380)

Summary:
Per release runbook, we'll need to have a version.txt to specify the current version. This is used as the source of truth and we shall update it after every branch cut. This PR adds version.txt and does necessary adjustments for setup.py to use it.

Pull Request resolved: https://github.com/facebookresearch/torcharrow/pull/380

Reviewed By: ejguan

Differential Revision: D37164812

Pulled By: bearzx

fbshipit-source-id: 9659a09f085a5fdb1b87511dc80701c1b43b2449

Add flex bison dependencies to nightly builds. (#382)

Summary:
- Added these dependencies to base image.

Pull Request resolved: https://github.com/facebookresearch/torcharrow/pull/382

Reviewed By: wenleix, bearzx

Differential Revision: D37198262

Pulled By: kgpai

fbshipit-source-id: 85c7124026d5c35ad6a9c59aed8c2bc12a0cc62b

Automated submodule update: velox (#375)

Summary:
This is an automated pull request to update the first-party submodule for [facebookincubator/velox](https://github.com/facebookincubator/velox).

New submodule commit: https://github.com/facebookincubator/velox/commit/0e4d3a5efece59b7d6a6a8f23ed7e4668d078e2e

X-link: https://github.com/facebookresearch/torcharrow/pull/375

Reviewed By: wenleix

Differential Revision: D37108171

fbshipit-source-id: 475c55d964c57ce204d3e5f1b8664b2c598b9f89

Doc update (#385)

Summary:
Changes in this PR:
* Put doc build and deploy into a separate workflow, so it doesn't run every time with a push. It also uploads the docs to the beta folder, which is accordingly created and linked in gh-pages branch.
* Added template parameters in the .rst files as NivekT suggested.
*  For the `istring_column.StringMethods` for now the best I could do is just removing the torcharrow prefix. I feel it's sort of related to the fact that StringMethods is not part of StringColumn. Importing it with an alias did not seem to work. We can keep investigating to find the best way to present it in the doc.

Pull Request resolved: https://github.com/pytorch/torcharrow/pull/385

Reviewed By: wenleix

Differential Revision: D37261768

Pulled By: bearzx

fbshipit-source-id: 2dc36b6a1ac5247c1ba3bf077652467492520f14

Format and correct README.md syntax (#370)

Summary:
as tiltle

Pull Request resolved: https://github.com/pytorch/torcharrow/pull/370

Reviewed By: wenleix

Differential Revision: D37078138

Pulled By: syscl

fbshipit-source-id: 41306ccdb26551559c79878e1c5a45e0d1155653

Update RC build CI workflow (#387)

Summary:
In this PR I made the following changes:
* added python 3.10 build
* added the pypi uploading part

One thing to note is, pypi doesn't allow uploading with the same name, but since we only manually trigger this workflow, we can always manually check if the files already exists and remove them if necessary. Another idea is to use TestPyPI (https://packaging.python.org/en/latest/guides/using-testpypi/).

Pull Request resolved: https://github.com/pytorch/torcharrow/pull/387

Reviewed By: ejguan

Differential Revision: D37286574

Pulled By: bearzx

fbshipit-source-id: 1c4ef40c40ebb2de132eab2f9391ddda39b72a7e

Automated submodule update: velox (#375)

Summary:
This is an automated pull request to update the first-party submodule for [facebookincubator/velox](https://github.com/facebookincubator/velox).

New submodule commit: https://github.com/facebookincubator/velox/commit/0e4d3a5efece59b7d6a6a8f23ed7e4668d078e2e

Pull Request resolved: https://github.com/pytorch/torcharrow/pull/375

Test Plan: Ensure that CI jobs succeed on GitHub before landing.

Reviewed By: wenleix

Differential Revision: D37296357

fbshipit-source-id: f9dc5de1da49cf7ef97ba7440b5a45122267200b

Include bison and flex in conda nightly build for ubuntu (#389)

Summary:
EZ, quick one liner change to fix the failing conda build on linux.

Pull Request resolved: https://github.com/pytorch/torcharrow/pull/389

Reviewed By: wenleix

Differential Revision: D37301242

Pulled By: bearzx

fbshipit-source-id: 596c5f65b1d8f33d3ad0d5fbbb7deb462116b466

Rename ChannelIndex to column_index_t (#388)

Summary:
Pull Request resolved: https://github.com/pytorch/torcharrow/pull/388

X-link: https://github.com/facebookexternal/presto_cpp/pull/775

X-link: https://github.com/facebookincubator/velox/pull/1811

title.

Reviewed By: mbasmanova

Differential Revision: D37129633

fbshipit-source-id: c52114e99498863ea1cb6ddf5817ae8a9aa9d730

Automated submodule update: velox (#392)

Summary:
This is an automated pull request to update the first-party submodule for [facebookincubator/velox](https://github.com/facebookincubator/velox).

New submodule commit: https://github.com/facebookincubator/velox/commit/f9bcd50c9177b6b11070aae4358f168ac0a1ddfd

Pull Request resolved: https://github.com/pytorch/torcharrow/pull/392

Test Plan: Ensure that CI jobs succeed on GitHub before landing.

Reviewed By: wenleix

Differential Revision: D37326277

fbshipit-source-id: 430332a58e9e47d46241f6bc08e7c9896e76b5f6

Update links in README (#393)

Summary: Pull Request resolved: https://github.com/pytorch/torcharrow/pull/393

Reviewed By: dracifer

Differential Revision: D37337620

Pulled By: wenleix

fbshipit-source-id: 71d0a44bbc61919ada0a4c5419969e60bc30bff9

Lazy update for dtype in tracing mode (#383)

Summary:
Pull Request resolved: https://github.com/pytorch/torcharrow/pull/383

X-link: https://github.com/facebookresearch/torcharrow/pull/383

Reviewed By: dracifer

Differential Revision: D37192215

fbshipit-source-id: 9c142bf07000efe3b1ea9d3176f4a80d1b6db39a

Pin range_v3 version to 0.12.0 (#396)

Summary:
Mac CI starts to fail today with
```
/Users/runner/work/torcharrow/torcharrow/_build/range-v3/include/meta/meta.hpp:30:32: error: unknown warning group '-Wreserved-identifier', ignored [-Werror,-Wunknown-warning-option]
```

Suspect
https://github.com/ericniebler/range-v3/commit/149e4a19c7b609aa79ae30b3ac69aebf17ab8f61
is the culprit. In any case use master version seems fragile.

Pull Request resolved: https://github.com/pytorch/torcharrow/pull/396

Reviewed By: bearzx

Differential Revision: D37358496

Pulled By: wenleix

fbshipit-source-id: 74dc98e0aed3b507b35bf325b9441cb57b916c38

Create add_tokens UDF (#384)

Summary:
- Adding and registering UDF for `add_tokens` which can operate on list of `int` and `str`

`pytest torcharrow/test/transformation/test_text_ops.py`

Pull Request resolved: https://github.com/pytorch/torcharrow/pull/384

Reviewed By: wenleix, parmeet

Differential Revision: D37315924

Pulled By: Nayef211

fbshipit-source-id: 81ce4fa6b45ea0681e87e9807a3b2f49337bdd0d

Automated submodule update: velox (#394)

Summary:
This is an automated pull request to update the first-party submodule for [facebookincubator/velox](https://github.com/facebookincubator/velox).

New submodule commit: https://github.com/facebookincubator/velox/commit/1a012cf1900de57c7f9c9e473b067e9a9934a450

Pull Request resolved: https://github.com/pytorch/torcharrow/pull/394

Test Plan: Ensure that CI jobs succeed on GitHub before landing.

Reviewed By: wenleix

Differential Revision: D37354396

fbshipit-source-id: ba5ca447e07606b69960a3047802486f0cc69f2a

Add clamp_list UDF (#397)

Summary:
Pull Request resolved: https://github.com/pytorch/torcharrow/pull/397

Basically apply clamp to each element in the list.  Used for sparse feature preproc in recommendation domain.

This UDF will be deprecated once TorchArrow supports lambda function.

Reviewed By: dracifer, bearzx

Differential Revision: D37370459

fbshipit-source-id: 8fb01a2ff3bf7cef1f199231d9693f0624907ecb

Automated submodule update: velox (#398)

Summary:
This is an automated pull request to update the first-party submodule for [facebookincubator/velox](https://github.com/facebookincubator/velox).

New submodule commit: https://github.com/facebookincubator/velox/commit/82d7763419e67be04eebc557c8489b6f701440b5

Pull Request resolved: https://github.com/pytorch/torcharrow/pull/398

Test Plan: Ensure that CI jobs succeed on GitHub before landing.

Reviewed By: wenleix

Differential Revision: D37391430

fbshipit-source-id: 14612c5e0b5013cf60cc371a7ca1a4e5f4a366c1

Remove install step in ubuntu.yml (#402)

Summary:
It's used to generate docs. Since we no longer generate docs per commit
(71f9c1a35f308969fcbe52198186605695aaf89b), we can also remove this to
save some time on CI test.

Pull Request resolved: https://github.com/pytorch/torcharrow/pull/402

Reviewed By: bearzx

Differential Revision: D37428114

Pulled By: wenleix

fbshipit-source-id: 285f9f1d1c3fd98f22933a4fa4fc0ec98d236f46

better error message with unsupported velox udfs (#400)

Summary:
As noted in issue https://github.com/pytorch/torcharrow/issues/230 we want to improve the error messages when missing velox UDFs to specify is it:
1. UDF doesn't exist at all
2. UDF exists, but doesn't accept the input types that user provided

This is implemented using similar code in https://github.com/facebookincubator/velox/blob/041f3759d6e4c070c2ecd2e01eae6a7be9d93957/velox/parse/TypeResolver.cpp#L112-L124

Pull Request resolved: https://github.com/pytorch/torcharrow/pull/400

Reviewed By: wenleix

Differential Revision: D37399459

Pulled By: bearzx

fbshipit-source-id: 75ca2cd818be30879a1e9b8e23d8a4ead02acedd

Automated submodule update: velox (#403)

Summary:
This is an automated pull request to update the first-party submodule for [facebookincubator/velox](https://github.com/facebookincubator/velox).

New submodule commit: https://github.com/facebookincubator/velox/commit/906c86a4e880c8687d19279e1a024688f1a9f9f3

Pull Request resolved: https://github.com/pytorch/torcharrow/pull/403

Test Plan: Ensure that CI jobs succeed on GitHub before landing.

Reviewed By: wenleix

Differential Revision: D37430607

fbshipit-source-id: 4a4cad19c2681881178ff6de744109c76bc4b58c

Minor changes to setup scripts (#395)

Summary:
* Update folly version to be consistent with Velox: https://github.com/facebookincubator/velox/blob/c4237370e40fce925a5c34bd805008248d42684f/scripts/setup-ubuntu.sh#L25
* Minor config flag change (e.g. disable testing), following https://github.com/facebookincubator/velox/blob/04a85f7cb7fcc2eaa3b30b1749c3d97b3bba8676/scripts/setup-macos.sh#L104
and  https://github.com/facebookincubator/velox/blob/04a85f7cb7fcc2eaa3b30b1749c3d97b3bba8676/scripts/setup-macos.sh#L109

Pull Request resolved: https://github.com/pytorch/torcharrow/pull/395

Reviewed By: bearzx

Differential Revision: D37478950

Pulled By: wenleix

fbshipit-source-id: 8b6ffa1377b0b6022e6e8550c08e711cab47dff2

Fix performance issues in gpt2_bpe_tokenizer (#401)

Summary:
Pull Request resolved: https://github.com/pytorch/torcharrow/pull/401

complex structures in c++ should be passed as const ref instead of value to avoid data copy. A bunch of functions was passing by value gpt2_bpe_tokenizer

Reviewed By: kevinwilfong, wenleix, Nayef211

Differential Revision: D37423480

fbshipit-source-id: 9b0dd5bf428214204d5d0322a08bd8506822382c

Automated submodule update: velox (#405)

Summary:
This is an automated pull request to update the first-party submodule for [facebookincubator/velox](https://github.com/facebookincubator/velox).

New submodule commit: https://github.com/facebookincubator/velox/commit/5f05648bdf4a7b20baf7dc30281db670aaadd0ed

Pull Request resolved: https://github.com/pytorch/torcharrow/pull/405

Test Plan: Ensure that CI jobs succeed on GitHub before landing.

Reviewed By: wenleix

Differential Revision: D37442044

fbshipit-source-id: 0f65c99d0085701d83fda27b579ecdcc26572fd7

Improve icolumn.py cc 1/4 test_numerical_column (#407)

Summary:
Pull Request resolved: https://github.com/pytorch/torcharrow/pull/407

Improves test coverage for icolumn.py through test_numerical_column. This stack gets icolumn.py to 86% coverage.

Reviewed By: OswinC

Differential Revision: D37492648

fbshipit-source-id: a90267d2372677722a8cdcae55d43fd146c4b9b3

Trigger CI on fbsync branch

Automated submodule update: velox

Automated submodule update: velox

Update Velox submodule

Automated submodule update: velox

Automated submodule update: velox

Automated submodule update: velox

Update Velox submodule

Enable single column str for drop/drop_duplicates/groupby

Also update _check_columns to ensure the input columns is always a sequence of str

Use latest Velox image to fix broken build.