use pybind11 primitive type converters instead of casting manually (#145)
Summary:
Pull Request resolved: https://github.com/facebookresearch/torcharrow/pull/145

Before this diff, our C++ interface used `py::int_` and `py::float_`, and then would call `py::cast<T>(val)` where `val` is either `py::int_` or `py::float_` and `T` is a primitive C++ type. This would break when we would try to provide Python types like `np.float32` or `np.int64`. A test like one of the ones this diff adds would encounter this kind of error:

```
======================================================================
ERROR: test_column_from_np_int_array (torcharrow.test.test_numerical_column_cpu.TestNumericalColumnCpu)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/scottas/fbsource/fbcode/buck-out/dev/gen/pytorch/torcharrow/torcharrow/test/tests#binary,link-tree/torcharrow/test/test_numerical_column_cpu.py", line 67, in test_column_from_np_int_array
    return self.base_test_column_from_np_int_array()
  File "/data/users/scottas/fbsource/fbcode/buck-out/dev/gen/pytorch/torcharrow/torcharrow/test/tests#binary,link-tree/torcharrow/test/test_numerical_column.py", line 495, in base_test_column_from_np_int_array
    c = ta.Column(a, device=self.device)
  File "/data/users/scottas/fbsource/fbcode/buck-out/dev/gen/pytorch/torcharrow/torcharrow/test/tests#binary,link-tree/torcharrow/icolumn.py", line 88, in Column
    return Scope._Column(data, dtype=dtype, device=device)
  File "/data/users/scottas/fbsource/fbcode/buck-out/dev/gen/pytorch/torcharrow/torcharrow/test/tests#binary,link-tree/torcharrow/trace.py", line 98, in wrapped
    res = fn(*args, **kwargs)
  File "/data/users/scottas/fbsource/fbcode/buck-out/dev/gen/pytorch/torcharrow/torcharrow/test/tests#binary,link-tree/torcharrow/scope.py", line 221, in _Column
    col._append(p)
  File "/data/users/scottas/fbsource/fbcode/buck-out/dev/gen/pytorch/torcharrow/torcharrow/test/tests#binary,link-tree/torcharrow/trace.py", line 98, in wrapped
    res = fn(*args, **kwargs)
  File "/data/users/scottas/fbsource/fbcode/buck-out/dev/gen/pytorch/torcharrow/torcharrow/test/tests#binary,link-tree/torcharrow/icolumn.py", line 1532, in _append
    self._append_value(value)
  File "/data/users/scottas/fbsource/fbcode/buck-out/dev/gen/pytorch/torcharrow/torcharrow/test/tests#binary,link-tree/torcharrow/velox_rt/numerical_column_cpu.py", line 88, in _append_value
    self._data.append(value)
TypeError: append(): incompatible function arguments. The following argument types are supported:
    1. (self: torcharrow._torcharrow.SimpleColumnBIGINT, arg0: int) -> None

Invoked with: <torcharrow._torcharrow.SimpleColumnBIGINT object at 0x7f5bdf7e43f0>, 1

----------------------------------------------------------------------
```
What's notable here is that the type we're trying to append is a `np.int64`. The error above is saying that append `arg0` should be `int`, but we have an object. That is, there's no conversion from `np.int64` to `int`. In the docs, pybind11 mentions [three options for defining these interfaces](https://pybind11.readthedocs.io/en/stable/advanced/cast/index.html). The third option is using C++ native types on the C++ side, and Python native types on the Python side, and depending on pybind11 to perform the type conversion. There are type conversions [already defined for numpy](https://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html). For primitive types, I think this approach is simplest.

The pybind11 docs mention automatic conversions for the numpy primitive types to the C++ primitive types, but we're not able to take advantage of it since our C++ interface does not use the C++ primitives.

This diff changes our C++ interface so that it does use the C++ primitive types, and then we're able to take advantage of the automatic conversion.

Reviewed By: wenleix, damianr99

Differential Revision: D33300430

fbshipit-source-id: 3affd256fa9c4b57dc2a6d32d56a4a3fcc91cbf6