Minor refactors to column getting methods
Summary:
1. Put `rename` in IDataFrame. Parameter name changed to `mapper` to be consistent with Pandas
2. Put `reorder` in IDataFrame. Pandas use `reindex`: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reindex.html . But since TorchArrow doesn't support complicated indexing so `reorder` seems a reasonable name.
3. Remove `keep`: Not in Pandas; and we can simply use `df[["col1", "col2"]]`.
    * A minor difference, though, is `df.keep(["col1", "col2"])` will keep the column ordering in original DF, while `df[["col1", "col2"]]` will keep column ordering as "col1", "col2"
4. Also remove the support for tuple in `__get_item__` to be consitent with Pandas:

```
>>> df = pd.DataFrame({"a": [1,2 , 3], "b": [4, 5, 6]})
>>> df[["a", "b"]]
   a  b
0  1  4
1  2  5
2  3  6
>>> df[("a", "b")]
Traceback (most recent call last):
  File "/Users/wxie/opt/miniconda3/envs/torcharrow/lib/python3.7/site-packages/pandas-1.3.4-py3.7-macosx-10.9-x86_64.egg/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: ('a', 'b')

>>> a = df["a"]
>>> a[[1, 2]]
1    2
2    3
Name: a, dtype: int64
>>> a[(1, 2)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wxie/opt/miniconda3/envs/torcharrow/lib/python3.7/site-packages/pandas-1.3.4-py3.7-macosx-10.9-x86_64.egg/pandas/core/series.py", line 966, in __getitem__
    return self._get_with(key)
  File "/Users/wxie/opt/miniconda3/envs/torcharrow/lib/python3.7/site-packages/pandas-1.3.4-py3.7-macosx-10.9-x86_64.egg/pandas/core/series.py", line 981, in _get_with
    return self._get_values_tuple(key)
  File "/Users/wxie/opt/miniconda3/envs/torcharrow/lib/python3.7/site-packages/pandas-1.3.4-py3.7-macosx-10.9-x86_64.egg/pandas/core/series.py", line 1016, in _get_values_tuple
    raise KeyError("key of type tuple not found and not a MultiIndex")
KeyError: 'key of type tuple not found and not a MultiIndex'
```

Differential Revision: D33288400

fbshipit-source-id: 11fc6d3173ce404e24a584b98124c91656f3fb55