fix help(torcharrow.functional)
Summary:
Too much Python black magic broke `help(torcharrow.functional)`:

```
>> import torcharrow
>> help(torcharrow.functional)
<several stack frames elided>
/usr/local/fbcode/platform010/lib/python3.8/inspect.py in getmembers(object, predicate)
    337     # attribute with the same name as a DynamicClassAttribute exists
    338     try:
--> 339         for base in object.__bases__:
    340             for k, v in base.__dict__.items():
    341                 if isinstance(v, types.DynamicClassAttribute):

TypeError: 'functools.partial' object is not iterable
```
We need to not auto-generate wrapped functions for requests for python
internal module members as this causes default functionality to break
in confusing ways.

Reviewed By: bearzx

Differential Revision: D36913734

fbshipit-source-id: 79da0b6f9c053269d90357703ac95f05a71babe5