More column getting API adjustment (#132)
Summary:
Pull Request resolved: https://github.com/facebookresearch/torcharrow/pull/132

1. Move `get_column` and `get_columns` as private -- Pandas doens't support it, and it can be easily supported by `df[]`
2. Move `slice_column` as private and remove support for syntax like `df["a":]`:
    * Pandas doesn't support `df["a":]`
```
>>> df2 = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6], "c": [7, 8, 9]})
>>> df2["b":]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wxie/opt/miniconda3/envs/torcharrow/lib/python3.7/site-packages/pandas-1.3.4-py3.7-macosx-10.9-x86_64.egg/pandas/core/frame.py", line 3430, in __getitem__
    indexer = convert_to_index_sliceable(self, key)
  File "/Users/wxie/opt/miniconda3/envs/torcharrow/lib/python3.7/site-packages/pandas-1.3.4-py3.7-macosx-10.9-x86_64.egg/pandas/core/indexing.py", line 2329, in convert_to_index_sliceable
    return idx._convert_slice_indexer(key, kind="getitem")
  File "/Users/wxie/opt/miniconda3/envs/torcharrow/lib/python3.7/site-packages/pandas-1.3.4-py3.7-macosx-10.9-x86_64.egg/pandas/core/indexes/numeric.py", line 244, in _convert_slice_indexer
    return super()._convert_slice_indexer(key, kind=kind)
  File "/Users/wxie/opt/miniconda3/envs/torcharrow/lib/python3.7/site-packages/pandas-1.3.4-py3.7-macosx-10.9-x86_64.egg/pandas/core/indexes/base.py", line 3719, in _convert_slice_indexer
    self._validate_indexer("slice", key.start, "getitem")
  File "/Users/wxie/opt/miniconda3/envs/torcharrow/lib/python3.7/site-packages/pandas-1.3.4-py3.7-macosx-10.9-x86_64.egg/pandas/core/indexes/base.py", line 5719, in _validate_indexer
    raise self._invalid_indexer(form, key)
TypeError: cannot do slice indexing on RangeIndex with these indexers [b] of type str
>>> df2["b":"c"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wxie/opt/miniconda3/envs/torcharrow/lib/python3.7/site-packages/pandas-1.3.4-py3.7-macosx-10.9-x86_64.egg/pandas/core/frame.py", line 3430, in __getitem__
    indexer = convert_to_index_sliceable(self, key)
  File "/Users/wxie/opt/miniconda3/envs/torcharrow/lib/python3.7/site-packages/pandas-1.3.4-py3.7-macosx-10.9-x86_64.egg/pandas/core/indexing.py", line 2329, in convert_to_index_sliceable
    return idx._convert_slice_indexer(key, kind="getitem")
  File "/Users/wxie/opt/miniconda3/envs/torcharrow/lib/python3.7/site-packages/pandas-1.3.4-py3.7-macosx-10.9-x86_64.egg/pandas/core/indexes/numeric.py", line 244, in _convert_slice_indexer
    return super()._convert_slice_indexer(key, kind=kind)
  File "/Users/wxie/opt/miniconda3/envs/torcharrow/lib/python3.7/site-packages/pandas-1.3.4-py3.7-macosx-10.9-x86_64.egg/pandas/core/indexes/base.py", line 3719, in _convert_slice_indexer
    self._validate_indexer("slice", key.start, "getitem")
  File "/Users/wxie/opt/miniconda3/envs/torcharrow/lib/python3.7/site-packages/pandas-1.3.4-py3.7-macosx-10.9-x86_64.egg/pandas/core/indexes/base.py", line 5719, in _validate_indexer
    raise self._invalid_indexer(form, key)
TypeError: cannot do slice indexing on RangeIndex with these indexers [b] of type str
```
   * NOTE: Pandas indeed support slicing by column name by using `iloc`: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#different-choices-for-indexing (but TorchArrow doesn't support `iloc`). So it might still be valid to support some kind of slicing by column name in the future.

Reviewed By: dracifer

Differential Revision: D33341932

fbshipit-source-id: c886a18dfc5332d13a6586e89d8a326a80e2c983